Added header from template
0x4447-office/0x4447_template_office_jekyll pull request #139
Opened 2021-04-01 23:26 UTC by x5hwuk7nc6jsudcc

2021-04-04 06:54 UTC, davidgatti requested changes
@x5hwuk7nc6jsudcc Looks good, but you missed this page: http://localhost:4000/get-discount.html

2021-04-04 09:51 UTC, x5hwuk7nc6jsudcc commented
Hi @davidgatti 

The relevant issue [#126](https://github.com/0x4447-office/0x4447_template_office_jekyll/issues/126) only references the 'schedule a demo' page. I'm happy to add the header template to additional pages, but just so we are clear, do you now only want this added to the 'get discount' page or do you want it added to _all_ pages on the site (excl. homepage)?

2021-04-06 16:03 UTC, davidgatti commented
> Hi @davidgatti
> 
> The relevant issue [#126](https://github.com/0x4447-office/0x4447_template_office_jekyll/issues/126) only references the 'schedule a demo' page. I'm happy to add the header template to additional pages, but just so we are clear, do you now only want this added to the 'get discount' page or do you want it added to _all_ pages on the site (excl. homepage)?

Good question, I want it to all the sub pages, not on the home page, same approach as here: https://consulting.0x4447.com/

2021-04-07 10:11 UTC, davidgatti approved these changes

2021-04-07 10:11 UTC, merged